-- 001 — alert-manager state.
--
-- alerts: one row per (fingerprint), updated as the alert transitions
--   through firing → resolved. Fingerprint is SHA-256 of
--   (tenant_id, rule_id, scope_labels-json), generated by the caller.
--
-- alert_history: append-only audit trail for compliance + UI timeline.
--
-- alert_silences: operator-applied suppressions; checked before
--   dispatching a notification. Silences are keyed by a label matcher
--   (JSONB equality + regex via matches_json).

CREATE TABLE IF NOT EXISTS alerts (
    fingerprint   TEXT PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    rule_id       TEXT NOT NULL,
    severity      TEXT NOT NULL,
    title         TEXT NOT NULL,
    description   TEXT,
    labels        JSONB NOT NULL DEFAULT '{}'::jsonb,
    annotations   JSONB NOT NULL DEFAULT '{}'::jsonb,
    state         TEXT NOT NULL CHECK (state IN ('firing','resolved','silenced')),
    starts_at     TIMESTAMPTZ NOT NULL,
    last_seen_at  TIMESTAMPTZ NOT NULL,
    resolved_at   TIMESTAMPTZ,
    notified_at   TIMESTAMPTZ,
    notify_count  INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_alerts_tenant_state ON alerts (tenant_id, state);
CREATE INDEX IF NOT EXISTS idx_alerts_last_seen ON alerts (last_seen_at DESC);

CREATE TABLE IF NOT EXISTS alert_history (
    id           BIGSERIAL PRIMARY KEY,
    fingerprint  TEXT NOT NULL,
    tenant_id    TEXT NOT NULL,
    event        TEXT NOT NULL, -- 'created' | 'updated' | 'notified' | 'resolved' | 'silenced'
    severity     TEXT,
    payload      JSONB NOT NULL,
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_alert_history_tenant_time ON alert_history (tenant_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS alert_silences (
    id            UUID PRIMARY KEY,
    tenant_id     TEXT NOT NULL,
    matcher       JSONB NOT NULL,
    reason        TEXT,
    created_by    TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_silences_tenant_expiry ON alert_silences (tenant_id, expires_at);
